spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tigmino?serverTimezone=GMT%2B00:00
    username: root
    password: Hafssa_02051
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 1000000000000MB
      max-request-size: 1000000000000MB

twilio:
  account:

  auth:
    token: 2c7f84c3949466f2f4fb543b9b9e93ef
  phoneNumber: "+12695750566"

project:
  image: assets/